#!/usr/bin/env python3
"""
TDX data import tool for Kronos fine-tuning.

Reads from TDengine (tdx.kline + tdx.adjust), computes back-adjustment from
dividend events, and converts to Kronos 6-field format (open, high, low,
close, vol, amt) saved as pickle files.

Features:
- Direct import of daily (1d) from TDengine
- Weekly (1w) and monthly (1M) generated by resampling from 1d
- Back-adjustment computed from TDengine adjust table events (no external API)
- Amount formula: prefer original data, fallback to mean(OHLC) * vol
- Historical data continuity analysis with gap reporting
"""

import argparse
import os
import pickle
import sys
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Optional

import numpy as np
import pandas as pd
from taosws import connect
from tqdm import tqdm

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

FEATURE_COLUMNS = ["open", "high", "low", "close", "vol", "amt"]

PERIOD_CONFIG = {
    "1d": {"source": "direct"},
    "1w": {"source": "resample", "base": "1d", "rule": "W-FRI"},
    "1M": {"source": "resample", "base": "1d", "rule": "1ME"},
}

OHLCV_AGG = {
    "open": "first",
    "high": "max",
    "low": "min",
    "close": "last",
    "volume": "sum",
    "amount": "sum",
}


# ---------------------------------------------------------------------------
# Gap / continuity analysis
# ---------------------------------------------------------------------------

def check_daily_continuity(
    df: pd.DataFrame, symbol: str, min_date=None, max_date=None
) -> list[dict]:
    """Check daily data for missing trading days."""
    if df.empty:
        return []

    date_col = "date" if "date" in df.columns else df.index.name
    if date_col and date_col != "date":
        dates = pd.to_datetime(df.index)
    else:
        dates = pd.to_datetime(df["date"]) if "date" in df.columns else pd.to_datetime(df.index)

    dates = sorted(dates.dropna().unique())
    if len(dates) < 2:
        return []

    d0 = pd.Timestamp(min_date) if min_date else dates[0]
    d1 = pd.Timestamp(max_date) if max_date else dates[-1]

    expected = pd.bdate_range(start=d0, end=d1, freq="C", weekmask="Mon Tue Wed Thu Fri")
    observed = set(pd.Timestamp(d).date() for d in dates)
    expected_set = set(d.date() for d in expected)

    missing = sorted(expected_set - observed)
    if not missing:
        return []

    return _group_consecutive_dates(missing, symbol, dates[0], dates[-1], d0, d1)


def _group_consecutive_dates(missing, symbol, first_date, last_date, d0, d1):
    """Group a sorted list of missing dates into consecutive gap records."""
    gaps = []
    span_days = (d1 - d0).days or 1

    start = end = missing[0]
    for i in range(1, len(missing)):
        if (missing[i] - missing[i - 1]).days == 1:
            end = missing[i]
        else:
            days = (end - start).days + 1
            gaps.append({
                "symbol": symbol,
                "start": str(start),
                "end": str(end),
                "days_missing": days,
                "pct": round(100 * days / span_days, 2),
            })
            start = end = missing[i]

    days = (end - start).days + 1
    gaps.append({
        "symbol": symbol,
        "start": str(start),
        "end": str(end),
        "days_missing": days,
        "pct": round(100 * days / span_days, 2),
    })
    return gaps


def summarize_gaps(all_gaps: dict[str, list]) -> str:
    """Generate a human-readable gap summary report."""
    if not all_gaps:
        return "No gaps detected. Data is continuous."

    lines = ["=" * 60, "DATA CONTINUITY REPORT", "=" * 60]
    total_stocks_affected = 0
    total_gaps = 0
    total_missing_days = 0

    for period, gaps in sorted(all_gaps.items()):
        if not gaps:
            continue
        total_stocks_affected += 1
        p_total_gaps = len(gaps)
        total_gaps += p_total_gaps
        lines.append(f"\n--- Period: {period} ({p_total_gaps} gaps) ---")

        by_symbol = defaultdict(list)
        for g in gaps:
            by_symbol[g["symbol"]].append(g)

        for sym, sym_gaps in sorted(by_symbol.items()):
            if "days_missing" in sym_gaps[0]:
                days = sum(g["days_missing"] for g in sym_gaps)
                total_missing_days += days
                lines.append(
                    f"  {sym}: {len(sym_gaps)} gap(s), {days} missing days total"
                )
                for g in sym_gaps[:3]:
                    lines.append(
                        f"    {g['start']} ~ {g['end']}: "
                        f"{g['days_missing']} days ({g['pct']}%)"
                    )
                if len(sym_gaps) > 3:
                    lines.append(f"    ... and {len(sym_gaps) - 3} more gap(s)")
            else:
                lines.append(f"  {sym}: {len(sym_gaps)} intraday gap(s)")

    lines.append(f"\n{'=' * 60}")
    lines.append(
        f"Summary: {total_gaps} gaps across {total_stocks_affected} periods"
    )
    if total_missing_days:
        lines.append(f"Total missing trading days: {total_missing_days}")
    lines.append("=" * 60)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Back-adjustment (from TDengine adjust events, no external API)
# ---------------------------------------------------------------------------

def _compute_back_adjust_factor(df: pd.DataFrame, events: list[dict]) -> np.ndarray:
    """Compute back-adjustment factor from dividend events.

    Factor accumulates from newest to oldest bar:
      factor[latest] = 1.0
      On dividend event: factor[bars before event] *= multiplier

    Multiplier formula (TDX standard):
      D = fenhong/10, S = songzhuangu/10, P = peigu/10, Pp = peigujia
      multiplier = C * (1+S+P) / (C - D + P*Pp)

    Returns:
        np.ndarray of shape [n_bars], dtype float64
    """
    n = len(df)
    factor = np.ones(n, dtype=np.float64)

    if not events:
        return factor

    events_sorted = sorted(events, key=lambda e: e['date'])
    df_dates = df.index.values
    raw_close = df['close'].values

    for evt in events_sorted:
        evt_date = np.datetime64(evt['date'])
        event_idx = int(np.searchsorted(df_dates, evt_date))
        if event_idx >= n:
            continue
        prev_idx = event_idx - 1
        if prev_idx < 0:
            continue
        C_before = raw_close[prev_idx]
        if C_before <= 0:
            continue

        D = evt['fenhong'] / 10.0
        S = evt['songzhuangu'] / 10.0
        P = evt['peigu'] / 10.0
        Pp = evt['peigujia']

        denominator = C_before - D + P * Pp
        if denominator <= 0:
            continue
        numerator = C_before * (1.0 + S + P)
        multiplier = numerator / denominator

        if abs(multiplier - 1.0) < 1e-12:
            continue

        factor[:event_idx] *= multiplier

    return factor


def _apply_adjustment(df: pd.DataFrame, factor: np.ndarray) -> pd.DataFrame:
    """Apply back-adjustment factor to OHLC columns."""
    df_adj = df.copy()
    for col in ['open', 'high', 'low', 'close']:
        if col in df_adj.columns:
            df_adj[col] = (df_adj[col].values * factor).astype(np.float32)
    df_adj['vol'] = df_adj['vol'].astype(np.float32)
    df_adj['amt'] = df_adj['amt'].astype(np.float32)
    return df_adj


# ---------------------------------------------------------------------------
# TDengine data access
# ---------------------------------------------------------------------------

def _resolve_market(code: str) -> str:
    """Map raw numeric code to market prefix.

    Returns 'sh', 'sz', or 'bj'.
    """
    if code.startswith(('60', '68')):
        return 'sh'
    elif code.startswith(('00', '30', '12', '16', '15')):
        return 'sz'
    elif code.startswith(('8', '4', '9')):
        return 'bj'
    return 'sz'  # fallback


def _code_to_symbol(code: str) -> str:
    """Convert raw numeric code to prefixed symbol (e.g. '000001' -> 'sz000001')."""
    market = _resolve_market(code)
    return f"{market}{code}"


def _symbol_to_code(symbol: str) -> str:
    """Convert prefixed symbol to raw numeric code (e.g. 'sz000001' -> '000001')."""
    if symbol.startswith(('sh', 'sz', 'bj')):
        return symbol[2:]
    return symbol


def _query_adjust_events(conn, code: str) -> list[dict]:
    """Query dividend events from TDengine adjust table.

    Returns list of event dicts sorted by date ascending.
    """
    events = []
    try:
        r = conn.query(
            f"select ts, fenhong, peigujia, songzhuangu, peigu "
            f"from tdx.a_{code} order by ts"
        )
        for row in r:
            ts, fh, pj, sz, pg = row
            fh, pj, sz, pg = float(fh), float(pj), float(sz), float(pg)
            if fh > 0 or sz > 0 or pg > 0:
                events.append({
                    'date': pd.Timestamp(ts).tz_localize(None),
                    'fenhong': fh,
                    'peigujia': pj,
                    'songzhuangu': sz,
                    'peigu': pg,
                })
    except Exception:
        pass  # no adjust data for this stock, leave unadjusted
    return events


def _query_daily_kline(conn, code: str) -> pd.DataFrame | None:
    """Query daily OHLCV from TDengine for a single stock.

    Returns DataFrame indexed by datetime with columns: open, high, low,
    close, vol, amt (float64). Returns None if insufficient data.
    """
    try:
        r = conn.query(
            f"select ts, open, high, low, close, volume, amount "
            f"from tdx.k_{code}_1d order by ts"
        )
    except Exception:
        return None

    rows = list(r)
    if len(rows) < 100:
        return None

    df = pd.DataFrame(
        rows,
        columns=['ts', 'open', 'high', 'low', 'close', 'vol', 'amt'],
    )
    df['ts'] = pd.to_datetime(df['ts']).dt.tz_localize(None)
    df = df.set_index('ts').sort_index()
    df = df.astype({c: np.float64 for c in ['open', 'high', 'low', 'close', 'vol', 'amt']})
    return df


def _discover_stocks_tdengine() -> list[str]:
    """Discover available stock symbols from TDengine kline tables.

    Returns prefixed symbols like ['sh600000', 'sz000001', ...].
    """
    conn = connect()
    try:
        r = conn.query("select distinct tbname from tdx.kline where cycle='1d'")
        symbols = []
        for row in r:
            tbname = row[0]  # k_000001_1d
            code = tbname.split('_')[1]
            symbols.append(_code_to_symbol(code))
        return sorted(symbols)
    finally:
        conn.close()


def _fetch_stock_daily(conn, symbol: str, dividend_type: str) -> pd.DataFrame | None:
    """Fetch and optionally adjust a single stock's daily data from TDengine.

    Args:
        conn: TDengine connection.
        symbol: Prefixed symbol like 'sz000001'.
        dividend_type: 'back' or 'none'.

    Returns:
        DataFrame with columns [date, stock_code, open, high, low, close,
        vol, amt] or None.
    """
    code = _symbol_to_code(symbol)
    df = _query_daily_kline(conn, code)
    if df is None:
        return None

    if dividend_type == "back":
        events = _query_adjust_events(conn, code)
        factor = _compute_back_adjust_factor(df, events)
        df = _apply_adjustment(df, factor)

    df = df.reset_index()
    df = df.rename(columns={'ts': 'date', 'index': 'date'})
    if 'date' not in df.columns:
        return None
    df['date'] = pd.to_datetime(df['date'], errors='coerce')
    df['stock_code'] = symbol
    return df


# ---------------------------------------------------------------------------
# Data import
# ---------------------------------------------------------------------------

class TdxDataImporter:
    """Import data from TDengine and convert to Kronos 6-field format.

    Parameters
    ----------
    dividend_type : str
        Price adjustment: 'back' (hfq) or 'none'.
    start_date : str, optional
        Filter start date (YYYY-MM-DD).
    end_date : str, optional
        Filter end date (YYYY-MM-DD).
    workers : int
        Number of parallel threads for data fetching.
    """

    def __init__(
        self,
        tdxdir: Optional[str] = None,  # kept for backward compat, ignored
        dividend_type: str = "none",
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        workers: int = 8,
    ):
        self.dividend_type = dividend_type
        self.start_date = start_date
        self.end_date = end_date
        self.workers = max(1, workers)
        self.gaps: dict[str, list[dict]] = defaultdict(list)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def discover_stocks(self, markets=("sh", "sz", "bj")) -> list[str]:
        """Discover available stock symbols from TDengine.

        Args:
            markets: Filter by market prefixes (default: all).

        Returns:
            Sorted list of prefixed symbols.
        """
        all_stocks = _discover_stocks_tdengine()
        if markets:
            all_stocks = [s for s in all_stocks if s[:2] in markets]
        return sorted(all_stocks)

    def import_period(
        self,
        stock_list: list[str],
        period: str = "1d",
    ) -> pd.DataFrame:
        """Import a single period for multiple stocks.

        Returns DataFrame with columns:
        stock_code, date, open, high, low, close, vol, amt
        """
        config = PERIOD_CONFIG.get(period)
        if config is None:
            raise ValueError(
                f"Unsupported period '{period}'. "
                f"Supported: {sorted(PERIOD_CONFIG.keys())}"
            )

        if config["source"] == "direct":
            return self._import_direct(stock_list)
        else:
            return self._import_resampled(stock_list, period, config)

    def build_dataset(
        self,
        stock_list: list[str],
        period: str = "1d",
        check_continuity: bool = True,
    ) -> dict[str, pd.DataFrame]:
        """Build the full {symbol: DataFrame} dataset for a period."""
        print(f"\n{'=' * 60}")
        print(f"Importing period: {period}")
        print(f"Stocks: {len(stock_list)}")

        df_all = self.import_period(stock_list, period)
        if df_all.empty:
            print(f"  WARNING: No data imported for period {period}")
            return {}

        dataset = {}
        for code, grp in df_all.groupby("stock_code"):
            symbol_df = self._to_kronos_format(grp)
            if symbol_df is None or symbol_df.empty:
                continue
            dataset[code] = symbol_df

        if check_continuity and period == "1d":
            for sym, sdf in dataset.items():
                gaps = check_daily_continuity(
                    sdf, sym, self.start_date, self.end_date
                )
                if gaps:
                    self.gaps[period].extend(gaps)
            if self.gaps.get(period):
                print(f"  Found {len(self.gaps[period])} daily gap(s)")

        if dataset:
            ranges = []
            for sym, sdf in dataset.items():
                ranges.append((sym, sdf.index[0], sdf.index[-1], len(sdf)))
            ranges.sort(key=lambda x: x[1])
            print(f"  Exported {len(dataset)} symbols")
            print(f"  Data range: {ranges[0][1].strftime('%Y-%m-%d')} ~ "
                  f"{ranges[-1][2].strftime('%Y-%m-%d')} "
                  f"(across {len(dataset)} symbols)")
        return dataset

    def save_dataset(
        self,
        dataset: dict[str, pd.DataFrame],
        output_dir: str,
        period: str = "1d",
        splits: Optional[dict[str, tuple[str, str]]] = None,
    ):
        """Save dataset to disk as pickle file(s)."""
        period_dir = os.path.join(output_dir, period)
        os.makedirs(period_dir, exist_ok=True)

        if splits:
            lookback_pad = 110
            split_order = ["train", "val", "test"]
            for split_name in split_order:
                s_start, s_end = splits[split_name]
                split_data = {}
                for sym, sdf in dataset.items():
                    if split_name == "train":
                        mask = (sdf.index >= s_start) & (sdf.index <= s_end)
                    else:
                        pad_start = pd.Timestamp(s_start) - pd.Timedelta(days=int(lookback_pad * 1.5))
                        mask = (sdf.index >= pad_start) & (sdf.index <= s_end)
                    subset = sdf[mask]
                    if not subset.empty:
                        split_data[sym] = subset

                fpath = os.path.join(period_dir, f"{split_name}_data.pkl")
                with open(fpath, "wb") as f:
                    pickle.dump(split_data, f)
                if len(split_data) == 0:
                    print(f"  WARNING: {split_name} split is empty! "
                          f"Date range ({s_start}, {s_end}) may not overlap "
                          f"with available data.")
                else:
                    pad_note = f" (padded from {pad_start.strftime('%Y-%m-%d')})" if split_name != "train" else ""
                    print(f"  Saved {fpath} ({len(split_data)} symbols){pad_note}")
        else:
            fpath = os.path.join(period_dir, "data.pkl")
            with open(fpath, "wb") as f:
                pickle.dump(dataset, f)
            print(f"  Saved {fpath} ({len(dataset)} symbols)")

    def print_gap_report(self):
        """Print the accumulated gap analysis report."""
        print(summarize_gaps(self.gaps))

    def get_gap_summary(self) -> dict:
        """Return structured gap summary for programmatic use."""
        summary = {}
        for period, gaps in self.gaps.items():
            summary[period] = {
                "total_gaps": len(gaps),
                "affected_symbols": len(set(g["symbol"] for g in gaps)),
                "details": gaps,
            }
        return summary

    # ------------------------------------------------------------------
    # Internal: data reading
    # ------------------------------------------------------------------

    def _import_direct(self, stock_list: list[str]) -> pd.DataFrame:
        """Import daily data from TDengine in parallel."""
        print(f"  Fetching from TDengine ({self.workers} threads, "
              f"adjust={self.dividend_type})...")

        result_parts = []

        def _fetch_one(symbol: str) -> pd.DataFrame | None:
            """Worker: one connection per thread."""
            conn = connect()
            try:
                return _fetch_stock_daily(conn, symbol, self.dividend_type)
            except Exception as e:
                print(f"  WARNING: Failed to fetch {symbol}: {e}")
                return None
            finally:
                conn.close()

        with ThreadPoolExecutor(max_workers=self.workers) as executor:
            futures = {executor.submit(_fetch_one, s): s for s in stock_list}
            with tqdm(total=len(stock_list), desc="  Fetching", unit="股",
                      ncols=80) as pbar:
                for future in as_completed(futures):
                    df = future.result()
                    if df is not None and not df.empty:
                        result_parts.append(df)
                    pbar.update(1)

        if not result_parts:
            return pd.DataFrame()

        df_all = pd.concat(result_parts, ignore_index=True)

        # Date filtering
        if self.start_date or self.end_date:
            if "date" in df_all.columns:
                date_series = pd.to_datetime(df_all["date"], errors="coerce")
                if self.start_date:
                    df_all = df_all[date_series >= pd.Timestamp(self.start_date)]
                if self.end_date:
                    df_all = df_all[date_series <= pd.Timestamp(self.end_date)]

        return df_all

    def _import_resampled(
        self, stock_list: list[str], period: str, config: dict
    ) -> pd.DataFrame:
        """Generate period by resampling from base period."""
        base_period = config["base"]
        rule = config["rule"]
        print(f"  Resampling from {base_period} -> {period} (rule={rule})")

        base_config = PERIOD_CONFIG[base_period]
        df_base = self._import_direct(stock_list)
        if df_base.empty:
            return pd.DataFrame()

        result_parts = []
        for code, grp in df_base.groupby("stock_code"):
            try:
                resampled = self._resample_ohlcv(grp, rule)
                if resampled is not None and not resampled.empty:
                    resampled["stock_code"] = code
                    result_parts.append(resampled)
            except Exception as e:
                print(f"  WARNING: Failed to resample {code}: {e}")

        if not result_parts:
            return pd.DataFrame()
        return pd.concat(result_parts, ignore_index=True)

    # ------------------------------------------------------------------
    # Internal: resampling
    # ------------------------------------------------------------------

    @staticmethod
    def _resample_ohlcv(df: pd.DataFrame, rule: str) -> Optional[pd.DataFrame]:
        """Resample OHLCV data to a new frequency."""
        df = df.copy()
        df["date"] = pd.to_datetime(df["date"], errors="coerce")
        df = df.set_index("date").sort_index()

        for col in ["open", "high", "low", "close"]:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")
        for col in ["volume", "amount"]:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

        ohlc_cols = [c for c in ["open", "high", "low", "close"] if c in df.columns]
        if len(ohlc_cols) < 4:
            return None

        valid_mask = df[ohlc_cols].notna().all(axis=1)
        if not valid_mask.any():
            return None

        resampled = df[valid_mask].resample(rule).agg(OHLCV_AGG)
        resampled = resampled.dropna(subset=ohlc_cols, how="all")
        resampled = resampled.reset_index()
        return resampled

    # ------------------------------------------------------------------
    # Internal: format conversion
    # ------------------------------------------------------------------

    def _to_kronos_format(self, df: pd.DataFrame) -> Optional[pd.DataFrame]:
        """Convert a single-stock DataFrame to Kronos 6-field format."""
        df = df.copy()

        if "date" in df.columns:
            df["date"] = pd.to_datetime(df["date"], errors="coerce")
            df = df.dropna(subset=["date"])
            df = df.set_index("date")
        elif df.index.name in ("date", "datetime"):
            df.index = pd.to_datetime(df.index, errors="coerce")

        df = df.sort_index()

        rename = {}
        for col in df.columns:
            if col == "volume":
                rename["volume"] = "vol"
            elif col == "amount":
                rename["amount"] = "amt"
        df = df.rename(columns=rename)

        for col in ["open", "high", "low", "close"]:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")

        if "vol" in df.columns:
            df["vol"] = pd.to_numeric(df["vol"], errors="coerce").fillna(0)
        if "amt" in df.columns:
            df["amt"] = pd.to_numeric(df["amt"], errors="coerce").fillna(0)

        need_amt = True
        if "amt" in df.columns:
            if df["amt"].notna().any() and (df["amt"] > 0).any():
                need_amt = False

        if need_amt:
            ohlc_cols = ["open", "high", "low", "close"]
            if all(c in df.columns for c in ohlc_cols) and "vol" in df.columns:
                mean_ohlc = df[ohlc_cols].mean(axis=1)
                df["amt"] = mean_ohlc * df["vol"]
            else:
                df["amt"] = 0.0

        keep = [c for c in FEATURE_COLUMNS if c in df.columns]
        df = df[keep]

        ohlc = [c for c in ["open", "high", "low", "close"] if c in df.columns]
        if ohlc:
            df = df.dropna(subset=ohlc, how="all")

        if df.empty:
            return None
        return df


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    p = argparse.ArgumentParser(
        description="TDX data import tool for Kronos fine-tuning (TDengine source)"
    )
    p.add_argument(
        "--symbols",
        nargs="*",
        help="Stock codes to import (e.g. sh600000 sz000001). "
             "If omitted, auto-discover all stocks from TDengine.",
    )
    p.add_argument(
        "--symbol-file",
        help="File with stock codes, one per line",
    )
    p.add_argument(
        "--periods",
        nargs="+",
        default=["1d"],
        choices=list(PERIOD_CONFIG.keys()),
        help="Periods to import (default: 1d). Supported: 1d, 1w, 1M",
    )
    p.add_argument(
        "--dividend-type",
        default="none",
        choices=["none", "back"],
        help="Price adjustment: back (hfq) or none (default)",
    )
    p.add_argument(
        "--output-dir",
        default="./data/tdx_import",
        help="Output directory (default: ./data/tdx_import)",
    )
    p.add_argument(
        "--start-date",
        help="Start date filter (YYYY-MM-DD)",
    )
    p.add_argument(
        "--end-date",
        help="End date filter (YYYY-MM-DD)",
    )
    p.add_argument(
        "--no-split",
        action="store_true",
        help="Save as single file instead of train/val/test splits",
    )
    p.add_argument(
        "--train-range",
        nargs=2,
        default=["2011-01-01", "2022-12-31"],
        metavar=("START", "END"),
        help="Training set date range (default: 2011-01-01 2022-12-31)",
    )
    p.add_argument(
        "--val-range",
        nargs=2,
        default=["2022-09-01", "2024-06-30"],
        metavar=("START", "END"),
        help="Validation set date range (default: 2022-09-01 2024-06-30)",
    )
    p.add_argument(
        "--test-range",
        nargs=2,
        default=["2024-04-01", "2025-06-05"],
        metavar=("START", "END"),
        help="Test set date range (default: 2024-04-01 2025-06-05)",
    )
    p.add_argument(
        "--no-continuity",
        action="store_true",
        help="Skip data continuity check",
    )
    p.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Limit to first N stocks (for testing, 0 = all)",
    )
    p.add_argument(
        "--workers",
        "-n",
        type=int,
        default=8,
        help="Parallel threads (default: 8)",
    )
    p.add_argument(
        "--list-stocks",
        action="store_true",
        help="List available stocks from TDengine and exit",
    )
    return p.parse_args()


def load_symbols(args) -> list[str]:
    """Resolve stock list from CLI args."""
    if args.symbols:
        return args.symbols

    if args.symbol_file:
        with open(args.symbol_file) as f:
            return [line.strip() for line in f if line.strip()]

    importer = TdxDataImporter()
    stocks = importer.discover_stocks()
    print(f"Auto-discovered {len(stocks)} stocks from TDengine")
    return stocks


def main():
    args = parse_args()

    if args.list_stocks:
        importer = TdxDataImporter()
        stocks = importer.discover_stocks()
        print(f"Found {len(stocks)} stocks from TDengine:")
        for s in stocks:
            print(f"  {s}")
        return

    stock_list = load_symbols(args)
    if not stock_list:
        print("ERROR: No stocks specified or discovered.")
        sys.exit(1)

    if args.limit > 0:
        stock_list = stock_list[: args.limit]
        print(f"Limited to first {args.limit} stocks")

    splits = None
    if not args.no_split:
        splits = {
            "train": tuple(args.train_range),
            "val": tuple(args.val_range),
            "test": tuple(args.test_range),
        }

    importer = TdxDataImporter(
        dividend_type=args.dividend_type,
        start_date=args.start_date,
        end_date=args.end_date,
        workers=args.workers,
    )

    for period in args.periods:
        dataset = importer.build_dataset(
            stock_list=stock_list,
            period=period,
            check_continuity=not args.no_continuity,
        )
        if not dataset:
            print(f"  SKIP: No data for period {period}")
            continue

        importer.save_dataset(
            dataset=dataset,
            output_dir=args.output_dir,
            period=period,
            splits=splits,
        )

    if not args.no_continuity:
        importer.print_gap_report()

    print(f"\nDone. Output saved to {args.output_dir}/")
    print("To use with Kronos, update finetune/config.py:")
    print(f"  self.dataset_path = \"{os.path.abspath(args.output_dir)}/1d\"")


if __name__ == "__main__":
    main()
